name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Run pipeline test
        run: |
          nextflow run main.nf \
            --fastq_dir test_data \
            --outdir out \
            -with-docker
